# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Marc Bruins
tagline:          'Blogging about mobile development with Xamarin with MvvmCross'
description:      'Hi i am <a href="https://twitter.com/MarcBruins" target="_blank">@MarcBruins</a>. I author this blog, create courses for Pluralsight and 
am a Developer Advocate. I speak at events, contribute to OSS, and I train technology thought leaders'
url:              http://hyde.getpoole.com
baseurl:          /
imagepath:        /public/img/

author:
  name:           'Marc Bruins'
  url:            https://twitter.com/MarcBruins

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Custom plugins
plugins: [jekyll-paginate,pygments.rb]