# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Marc Bruins
tagline:          'Blogging about mobile development with Xamarin with MvvmCross'
description:      'Hi i am <a href="https://twitter.com/MarcBruins" target="_blank">@MarcBruins</a>. I author this blog and am a Xamarin & Microsoft MVP. I work as a Xamarin Enterprise Consultant, speak at conferences, and contribute to OSS'
url:              http://hyde.getpoole.com
baseurl:          /
imagepath:        /public/img/
excerpt_separator: '<!--more-->'
permalink: /:title

author:
  name:           'Marc Bruins'
  url:            https://twitter.com/MarcBruins

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Custom plugins
plugins: [jekyll-paginate,pygments.rb,jekyll-feed]